### ISSUE TITLE
Limitless-onleave-autooff - Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by Klizzy** [sebauer/if-this-then-node#12]
first off, tanks for your awesome work!
The standard zone on/off plugin is working as intended, but the autoleave doesn't. 
The only difference on my setup from your Setup-guide is the start of the node server.
Instead of starting the server with `node start` i had to use `node server` to run it.
i don't have any experience with node, but i don't think that this is the problem, because the zone off request ist working. 

Here is an Screenshot of the Log output:
![bildschirmfoto 2016-05-23 um 23 06 13](https://cloud.githubusercontent.com/assets/15422170/15484591/03669fb2-213b-11e6-8a4d-b0b40eb49217.png)

**Comment by sebauer** [comment]
Hi @Klizzy ,

it looks like there's a configuration error with the configuration of your IFTTT request.

As from your screenshot you're calling the limitless-zone-onoff plugin with the configuration of the limitless-onleave-autooff. Because of that the onoff-plugin is missing the "onoff" parameter. Check your IFTTT config and replace "action": "limitless-zone-onoff" by  "action": "limitless-zone-onoff" and you should be fine :)

**Comment by Klizzy** [comment]
ah okay, so am i right that in your Setup Guide for the Plugin limitless-onleave-autooff, the ifttt action should be `"action": "limitless-onleave-autooff"` instead of `"action": "limitless-zone-onoff"` ?

**Comment by sebauer** [comment]
Shame on me! You're right, there's a mistake in my setup guide. I'll fix that.

**Comment by Klizzy** [comment]
Okay, thank you ☺️
