### ISSUE TITLE
Cannot add IFTTT channel

### ISSUE THREAD

**Issue by jamborta** [sebauer/if-this-then-node#5]
Hi Sebastian,

I wanted to try out your plugin to setup ifttt commands to control some limitless led bulbs. I have installed it and started up the server, seems it is all up and running, but when I want to activate the channel in ifttt, it just times out.

I have it running here: http://212.56.75.189:1337/

did I miss something to setup?

many thanks

**Comment by sebauer** [comment]
Hey there!

Yes, unfortunately IFTTT expects WordPress to be running on port 80 and does not accept anything else. So either you do a remapping while port-forwarding in your router (external port 80 goes to port 1337 on your system) or change the port, if-this-then-node is running on to 80. You'll find that in the following line: https://github.com/sebauer/if-this-then-node/blob/master/server.js#L63

But I would suggest doing the first option, because I suspect you have a port forwarding anyways. If not you should consider that because I would not recommend to have your complete system exposed to the outside world.

**Comment by jamborta** [comment]
thank you. I'll try that.
